export const actionTypes = {
  GET_ITEMS: 'GET_ITEMS',
  SET_ITEMS: 'SET_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ITEM_REMOVED: 'ITEM_REMOVED',
  ITEM_OPERATION_FAILED: 'ITEM_OPERATION_FAILED'
};
